### ISSUE TITLE
new Mesh class lacks meshio_type attribute

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#579]
A couple of my scripts broke after #556, raising, e.g.,

> AttributeError: 'MeshLine1' object has no attribute 'meshio_type'

I see that this is still handled in the usual cases by [`to_meshio`](https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/skfem/io/meshio.py#L143) or [`to_file`](https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/skfem/io/meshio.py#L153) which use

https://github.com/kinnala/scikit-fem/blob/e0703948a5d5ed18f78c935a9d6929f76a104648/skfem/io/meshio.py#L11-L22

The failing scripts weren't using either of these functions from `skfem.io.meshio` because they needed to geometrically transform the `skfem.Mesh`; e.g. the `MeshLine` was laid along the _z_-axis with

```python
 meshio.Mesh(
                     np.array([[0., 0., z] for z in mesh.p[0]]),
                     ...
```
and a `MeshQuad` in the _yz_-plane with
```python
          meshio.Mesh(
                 (self.transform @ self.mesh.p).T,
                 ...
```
where `self.transform` is loaded from
```json
   "transform": [[0, 0],
		  [-1, 0],
		  [0, -1]],
```

As I'm writing custom output functions for these cases anyway I can just hard-code `"line"`, `"quad"`, &c., or
```python
from skfem.io.meshio import TYPE_MESH_MAPPING
```
and then use `TYPE_MESH_MAPPING[type(m)]` for `m: skfem.Mesh`, but I wanted to check whether this excision was deliberate or an oversight.

**Comment by kinnala** [comment]
Basically anything that's not tested may be missing and apparently `meshio_type` was not included in the test suite. Do you think we should include it? If yes, we should implement a property which fetches it from `TYPE_MESH_MAPPING`. On the otherhand, next release will be 3.0.0 anyways so we can do small backwards-incompatible modifications if required.

**Comment by gdmcbain** [comment]
There are a failed and a successful attempt at fixing this in #580 and #584 respectively, but as discussed under the latter I'm inclined to leave this to user-level makeshifts.
